### ISSUE TITLE
Packages are broken.

### ISSUE THREAD

**Issue by actuallySoheil** [AtomMaterialUI/a-file-icon-idea#446] opened 2024-04-05 11:39 UTC
**Describe the bug:**
Basically, when I change the view to "Production" instead of "Project" in IntelliJ, I normally see packages and resources like this:
![image](https://github.com/mallowigi/a-file-icon-idea/assets/124730657/4229f97e-26da-4a9e-831f-7550bbe7e0d1)

However, by using the plugin, packages get little messy, and it shows me the full path in some packages:
![image](https://github.com/mallowigi/a-file-icon-idea/assets/124730657/847a08e9-f9b9-4ed9-bb90-1152afff27d0)

**To Reproduce:**
1. Change view to "Production" instaed of "Project"
2. See the bug.

**Expected Behavior**
1. Packages should not be like the images shown above

**Environment**
IntelliJ IDEA 2024.1 (Community Edition)
Build #IC-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry:
  project.tree.structure.show.url=false
  ide.experimental.ui=true
Non-Bundled Plugins:
  Lombook Plugin (241.14494.240)
  izhangzhihao.rainbow.brackets (2024.2.2-241)
  com.demonwav.minecraft-dev (2024.1-1.7.4)
  com.almightyalpaca.intellij.plugins.discord (1.12.0)
  com.mallowigi (95.0.0)
Kotlin: 241.14494.240-IJ

**Comment by mallowigi** [comment] 2024-04-05 13:29
Are you sure these screenshots differ only by having the plugin enabled or disabled ?

**Comment by actuallySoheil** [comment] 2024-04-10 09:27
yes. I'm 100 percent sure

**Comment by mallowigi** [comment] 2024-05-11 15:25
I can't reproduce.

Are you sure you don't have this option enabled: 
![CleanShot 2024-05-11 at 18 24 59@2x](https://github.com/mallowigi/a-file-icon-idea/assets/5015756/39ae2bbb-4d6a-4536-8c94-11f70065d401)

**Comment by actuallySoheil** [comment] 2024-05-11 18:20
It seems that packages that don't have a custom icon get this issue

**Comment by actuallySoheil** [comment] 2024-05-11 18:20
what theme are you using? @mallowigi

**Comment by actuallySoheil** [comment] 2024-05-12 16:43
![Screenshot 2024-05-12 201204](https://github.com/mallowigi/a-file-icon-idea/assets/124730657/63af48a9-568b-45db-ba6b-606fd656c6ee)

**Comment by actuallySoheil** [comment] 2024-05-12 16:43
I disabled "Compact Directories" and I still have this issue.

**Comment by actuallySoheil** [comment] 2024-05-12 16:46
https://github.com/mallowigi/a-file-icon-idea/assets/124730657/86048385-52d0-4b87-92ee-b281aaccf1ec

**Comment by actuallySoheil** [comment] 2024-05-12 16:49
https://github.com/mallowigi/a-file-icon-idea/assets/124730657/55a8ca63-0444-4b5a-981d-67f9016ce076

**Comment by actuallySoheil** [comment] 2024-05-12 16:56
![image](https://github.com/mallowigi/a-file-icon-idea/assets/124730657/d0bdf496-6fbd-40ef-8fa7-dbf423a00903)

**Comment by mallowigi** [comment] 2024-08-17 21:54
Follow up: I managed to reproduce and so far I couldn't find a fix for this issue, it is very strange, especially since it works fine on the "Project" view.

But there's a fix until I find something that works: simply disable the "Hollow Folders" setting and it will render ok.

**Comment by mallowigi** [comment] 2024-12-21 18:53
Closing due to lack of time investigating this.

**Closed by mallowigi** 2024-12-21 18:53 UTC
